### ISSUE TITLE
Cronhub CLI V1

### ISSUE THREAD

**Issue by tiggreen** [cronhub-app/product-roadmap#1]
A command line interface that eases the process of integration of your cronjob with Cronhub monitors. 

Currently, you have to manually integrate Cronhub monitors with your cron jobs and it's not ideal. I think it could be better.

**Comment by umpirsky** [comment]
How will integration look with CLI?

**Comment by tiggreen** [comment]
Probably a binary file that you can download and run using your Cronhub API key @umpirsky. 

E.g. You can run `cronhub setup` on your system and it will automatically create cronhub monitors based on your system cron jobs.  What do you think?

**Comment by umpirsky** [comment]
I see, but you still need to ping urls? Makes sense.

**Comment by tiggreen** [comment]
yes!

**Comment by tiggreen** [comment]
This is done! https://docs.cronhub.io/cronhub-cli.html#install-the-cli-binary-using-curl
