### ISSUE TITLE
Cronhub API

### ISSUE THREAD

**Issue by tiggreen** [cronhub-app/product-roadmap#3]
Having an API will allow Cronhub users to pull the status of their monitors. The API is also a foundation for many things I want to accomplish like shared dashboard, heroku add-on, etc.

**Comment by Faqahat** [comment]
Definitely needed

**Comment by tiggreen** [comment]
Going to start working on this today. Excited to get it released soon. 👍

**Comment by tiggreen** [comment]
This is done!
