### ISSUE TITLE
Dashboard has weird spacing on the y axis

### ISSUE THREAD

**Issue by ephraimkunz** [cronhub-app/product-roadmap#7]
See screenshot:
<img width="1428" alt="screen shot 2018-08-12 at 7 47 12 am" src="https://user-images.githubusercontent.com/10914093/44003226-157726ac-9e04-11e8-8f65-f86434382549.png">

Number of times jobs ran in the past month has some ticks at 2.5, 7.5, 12.5. This seems like a weird place to put ticks, as you can't run 1/2 of a job.

**Comment by tiggreen** [comment]
Totally agree, @ephraimkunz! Thanks for flagging. Will fix it soon.

**Comment by tiggreen** [comment]
This is now fixed @ephraimkunz :)
